markdown:         kramdown
highlighter:      rouge

title:            Asteroids
tagline:          'BMSTU practice project'
description:      '<a href="https://github.com/jexwerquez" target="_blank">Rogaleva Yulia</a> OOP practice project.'
url:              https://jexwerquez.github.io
baseurl:          '/'

paginate:         5
remote_theme: jexwerquez/Asteroids
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

sidebar_home_link:  true
